Nerdfee/Models/Article.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nerdfee.Models
{
    public class Article
    {
        public Guid Id { get; set; }
        [JsonProperty(PropertyName = "id")]
        public string FacebookId { get; set; }
        [JsonProperty(PropertyName = "message")]
        public string Text { get; set; }
        [JsonProperty(PropertyName = "created_time")]
        public DateTime Erstellt { get; set; }
        public string Kategorie { get; set; }
        public string Teaser { get; set; }
        public string Titel { get; set; }
        public long ThreadId { get; set; }
        public DateTime? Veroeffentlicht { get; set; }
    }
}

Nerdfee/Models/ArticleImage.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Nerdfee.Models
{
    public class ArticleImage
    {
        public Guid Id { get; set; }
        public Guid ArticleId { get; set; }
        public short OrderBy { get; set; }
        public byte[] Data { get; set; }
    }
}

Nerdfee/Controllers/ArtikelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using Nerdfee.Contracts;
using Newtonsoft.Json;
using System.IO;
using Nerdfee.Data;

namespace Nerdfee.Controllers
{
    public class ArtikelController : Controller
    {
        private readonly NerdfeeContext _context;

        public ArtikelController(NerdfeeContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Show(Guid id)
        {
            var hasImage = _context.ArticleImages.Any(x => x.ArticleId == id);
            ViewBag.HasImage = hasImage;
            return View(_context.Articles.First(x => x.Id == id));
        }

        public FileStreamResult GetPicture(Guid id)
        {
            var pic = _context.ArticleImages.FirstOrDefault(x => x.ArticleId == id);
            if (pic == null)
                return null;
            Stream stream = new MemoryStream(pic.Data);
            return new FileStreamResult(stream, "images/png");
        }
    }
}

Nerdfee/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.Net;
using Nerdfee.Contracts;
using Newtonsoft.Json;
using System.IO;
using Nerdfee.Models;
using Nerdfee.Data;
using System.Net.Http;

namespace Nerdfee.Controllers
{
    public class HomeController : Controller
    {
        private static string Token = "EAACEdEose0cBAASsb6ZAL3G3hC3OH5ZCNf7IR3sUcZBvCwPN9d0CkxYMGxJ4OxRAwWO1oftfNSIGYoZC9tJZBZAVpOMEGHFdan6sQfKRgPTr7Kj4JUnTZCFAlBZCKE7D5iggvSs1ZB3a0KZCZCyUNqelvNe4ZCYS6s6f1Ub9MgB1D1DM7jupJXS3ZBGzARcUpDvcEAim91qwlI58P3AZDZD";

        private readonly NerdfeeContext _context;

        public HomeController(NerdfeeContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {            
            return View(_context.Articles.OrderByDescending(x=>x.Erstellt).Take(5));
        }

        public IActionResult Sync()
        {
            var items = new List<Article>();
            
            //_context.ArticleImages.RemoveRange(_context.ArticleImages);
            //_context.SaveChanges();

            var feed = GetData<FeedResponse>("https://graph.facebook.com/v2.9/nerdfee/feed?from=Nerdfee&access_token={0}&format=json&method=get");
            while(feed != null && feed.Data.Count > 0)
            {
                items.AddRange(feed.Data);
                if (feed.Paging == null || string.IsNullOrEmpty(feed.Paging.Next))
                    break;
                feed = GetData<FeedResponse>(feed.Paging.Next);
            }

            foreach (var item in items)
            {
                if (item.Text == null) continue;
                if (item.Text.Length > 200)
                {
                    var parts = item.Text.Split('\n');
                    item.Titel = parts[0];
                    var i = 1;
                    var teaser = "";
                    while (teaser.Length < 150)
                    {
                        if (parts.Length <= i)
                            break;
                        teaser += parts[i++] + "\n";
                    }
                    item.Teaser = teaser;
                    item.Veroeffentlicht = item.Erstellt;
                    var update = _context.Articles.FirstOrDefault(x => x.FacebookId == item.FacebookId);
                    if (update != null)
                    {
                        update.Titel = item.Titel;
                        update.Teaser = item.Teaser;
                        update.Veroeffentlicht = item.Erstellt;
                    }
                    else
                    {
                        _context.Add(item);
                    }
                }
            }
            _context.SaveChanges();

            foreach (var article in _context.Articles)
            {
                //if (_context.ArticleImages.Any(x => x.ArticleId == article.Id))
                //    continue;
                string url = GetPictureUrl(article);
                if (!string.IsNullOrEmpty(url))
                {
                    try
                    {
                        var img = new ArticleImage();
                        img.ArticleId = article.Id;
                        img.OrderBy = 0;
                        img.Data = DownloadImage(url);
                        _context.ArticleImages.Add(img);
                    }catch(Exception ex) { }
                }
            }

            _context.SaveChanges();

            return null;
        }

        private byte[] DownloadImage(string url)
        {
            var httpClient = new HttpClient();
            var r = httpClient.GetStreamAsync(url);
            r.Wait();            
            var memoryStream = new MemoryStream();
            using (memoryStream)
            {
                var t = r.Result.CopyToAsync(memoryStream);
                t.Wait();
                memoryStream.Seek(0,SeekOrigin.Begin);
                return memoryStream.ToArray();
            }
        }

        private T GetData<T>(string url)
        {
            var r = WebRequest.Create(string.Format(url, Token));
            var re = r.GetResponseAsync();
            re.Wait();
            var s = re.Result.GetResponseStream();
            var serializor = JsonSerializer.Create();
            var feed = serializor.Deserialize<T>(new JsonTextReader(new StreamReader(s)));
            return feed;
        }

        private string GetPictureUrl(Article item)
        {
            try
            {
                var feed = GetData<PictureResponse>("https://graph.facebook.com/v2.9/" + item.FacebookId + "?fields=picture&access_token={0}&format=json&method=get");
                if(feed != null && feed.PictureUrl != null)
                {
                    return string.Format("https://graph.facebook.com/v2.9/{1}/picture?type=normal&access_token={0}", Token, feed.Id.Split('_')[1]);
                }
            }
            catch (Exception ex)
            {
            }
            return null;
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Impressum()
        {

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

Nerdfee/Views/Artikel/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Nerdfee/Views/Artikel/Show.cshtml
@model Nerdfee.Models.Article

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!-- Post Content -->
<article>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                @if (ViewBag.HasImage)
                {                
                    <img src="@Url.Action("GetPicture", "Artikel", new { id = Model.Id })" />
                }
                @foreach (var t in Model.Text.Split('\n'))
                {
                    <p>@t</p>
                }
            </div>
        </div>
    </div>
</article>

<div id="disqus_thread"></div>  
<script>

var disqus_config = function () {
    this.page.url = 'http://nerdfee.azurewebsites.net/Artikel/Show/@Model.Id';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '@Model.ThreadId'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    this.page.title = '@Model.Titel';
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://nerdfee.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

Nerdfee/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}


<!-- Main Content -->
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <p>
                Die Facebook-Seite Nerdfee schwirrt seit September 2016 im Netz herum. 
            </p>
            <p>
                Warum? Was will die? Was kann die?
            </p>
            <p>
                Bei der Nerdfee handelt es sich um Sophie Helmke, die 1987 im grauen Ruhrpott das Licht der Welt erblickte. Auch wenn es nicht ganz ihre Zeit war, hing die kleine Sophie mit dem Herzen schon immer an den 80ern, denn dort wimmelte es nur so vor Helden und Abenteuern, die ihr kleines Leben bunter machten.
            </p>
            <p>
                Sophie hatte schon immer eine Vorliebe für das Schreiben von Texten und so enstand eines Tages die "Nerdfee". Hier wird ordentlich rumgenerdet, über alles was das Kind im Herzen zum Hüpfen oder Kotzen bringt:
            </p>
            <p>
                Games, Comics, Serien, Filme und Toys der vergangenen, heutigen und kommenden Tage, werden hart aber herzlich rezensiert. Auch die ein oder andere Alltags-Anekdote aus ihrem nerdigen Leben findet den Weg auf das virtuelle Papier.
            </p>
            <p>
                <img src="~/images/profile.jpg" alt="Nerdfee" class="img" />
            </p>
        </div>
    </div>
</div>

Nerdfee/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Kontakt";
}


<div class="well">
    <p>Du hast eine Anfrage, Rückmeldung oder magst einfach mal nerdige Grüsse senden?</p>

    <p>Schreib der Nerdfee:</p>

    <p>Nerdfee@Nerdfee.de</p>
</div>
<ul class="pager">
    <li class="next">
        <a asp-area="" asp-controller="Home" asp-action="Impressum">Impressum</a>
    </li>
</ul>

Nerdfee/Views/Home/Impressum.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Impressum</h2>


<div class="well">
<address>
    Sophie Helmke <br/>
    Am Linckhof 31<br />
    41470 Neuss<br />
    <abbr title="Email">E-Mail:</abbr>
    Nerdfee@Nerdfee.de
</address>

</div>

Nerdfee/Views/Home/Index.cshtml
@{
}

    <!-- Main Content -->
    <div class="container">  
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">      
                @foreach (var item in Model)
                {
                    <div class="post-preview">
                        <a asp-area="" asp-controller="Artikel" asp-action="Show" asp-route-id="@item.Id" asp-fragment="disqus_thread">
                            <h2 class="post-title">
                                @item.Titel
                            </h2>
                            <h3 class="post-subtitle">
                                @item.Teaser
                            </h3>
                        </a>
                        <p class="post-meta">Posted on @item.Erstellt.ToString("dd. MMMM yyyy HH:mm")</p>
                    </div>
                    <hr>
                }
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">meeeehr &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

Nerdfee/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nerdfee</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Nerdfee</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Nerdfee</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <!-- Theme JavaScript -->
        <script src="~/js/clean-blog.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <!-- Theme JavaScript -->
        <script src="~/js/clean-blog.min.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Nerdfee/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nerdfee</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/clean-blog.css" />
        <!-- Custom Fonts -->
        <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet" type="text/css">
        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/clean-blog.min.css" asp-append-version="true" />
        <!-- Custom Fonts -->
        <link href="~/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>    
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Nerdfee</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Index">Artikel</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="About">Über</a>
                    </li>
                    <li>
                        <a asp-area="" asp-controller="Home" asp-action="Contact">Kontakt</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('@Url.Content("~/images/header.jpg")')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Nerdfee</h1>
                        <hr class="small">
                        <span class="subheading">The empire wants you!</span>
                    </div>
                </div> 
            </div>
        </div>
    </header>

    <div class="container body-content">
        @RenderBody()
        <hr />
        
    </div>

    
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://www.facebook.com/Nerdfee">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.instagram.com/nerdfee/">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://twitter.com/nerdfee">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Nerdfee 2017</p>
                </div>
            </div>
        </div>
    </footer>


    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <!-- Theme JavaScript -->
        <script src="~/js/clean-blog.js"></script>
        <script id="dsq-count-scr" src="//nerdfee.disqus.com/count.js" async></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <!-- Theme JavaScript -->
        <script src="~/js/clean-blog.min.js"></script>
        <script id="dsq-count-scr" src="//nerdfee.disqus.com/count.js" async></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>